language: c
script: make
before_install:
- openssl aes-256-cbc -K $encrypted_a2ccd447d104_key -iv $encrypted_a2ccd447d104_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
- scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa  ./LICENSE ./hello root@zhouxin.ltd:/root/pkg
